### ISSUE TITLE
ggrepel functionality?

### ISSUE THREAD

**Issue by shuckle16** [tdhock/directlabels#20]
Hi, thanks for making an awesome package! I use it a lot for charts at work.

Sometimes, though, I have several time series and the labels get clumped together. 

I'm also a user of ggrepel (https://github.com/slowkow/ggrepel) and was wondering if there was an avenue for combining the ideas from ggrepel with directlabels?

**Comment by tdhock** [comment]
hi there @shuckle16 I don't think ggrepel is relevant because it solves the "labeling individual points on scatterplots" whereas directlabels solves the "replace a legend in order to label each group of similar points/lines/etc"

if you have lots of time series I would recommend one of the "smart" positioning methods such as last.polygons or last.qp http://directlabels.r-forge.r-project.org/docs/lineplot/plots/bodyweight.html
